Description: Creates an S3 Bucket

Parameters:
  BucketName:
    Type: String

Conditions:
  IsDefaultRegion: !Equals [!Ref AWS::Region, us-east-1]

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - ${prefix}-${BucketName}
        - prefix: !If [IsDefaultRegion, !Ref AWS::AccountId, !Ref AWS::Region]
