Description: Creates a user and a managed policy with readonly S3 access

Parameters:
  UserName:
    Type: String

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      ManagedPolicyArns: 
        - !Ref Policy

  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: S3 Read Only access
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List* 
            Resource: arn:aws:s3:::*

        